name: Deploy FastAPI Application

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # - name: Run tests
    #   run: |
    #     pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Add SSH key to known hosts
      run: |
        echo "${{ secrets.SSH_KNOWN_HOST }}" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Installing SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to EC2
      run: |
        rsync -av --exclude '.git*' --exclude '.github' --exclude 'venv' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/backend/
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          cd /home/ubuntu/backend/
          # Assuming you have a virtual environment set up
          source venv/bin/activate
          # Install any new dependencies
          pip install -r requirements.txt
          # Kill the current Uvicorn process if running
          pkill -f uvicorn
          # Start Uvicorn in the background
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
        EOF

